### ISSUE TITLE
Todo's

### ISSUE THREAD

**Issue by RudigerBrecht** [evankielley/GDD#1]
- [x]  Documentation for code | online documentation ???
- [x]  Remove unused folder from gh-pages branch
- [x]  Remove presentation folder form master branch ?
